### ISSUE TITLE
SystemStackError -Logging error with require 'dicom' + include DICOM

### ISSUE THREAD

**Issue by vas1468** [dicom/ruby-dicom#73]
That's the only log I am getting. 

`SystemStackError (stack level too deep):
  dicom (0.9.6) lib/dicom/general/logging.rb:148`

Ruby 1.9.3
dicom 0.9.6
Ubuntu 16.04.3

**Comment by dicom** [comment]
I've never seen this behaviour before. Quite strange. Are you able to try with a more recent version of Ruby?

Regards,
Chris

**Comment by vijendra** [comment]
Even I am getting this error, though bnt sure, if it is ruby-dicom error. Rails 4.0.9 application using ruby-dicom was working fine. Recently added code to upload the files to AWS-S3 and started getting this error. 
Here is the trace from console.

Loading production environment (Rails 4.0.9)
2.2.9 :001 > s3 = Aws::S3::Resource.new
SystemStackError: stack level too deep
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/dicom-0.9.8/lib/dicom/general/logging.rb:148:in `logger'
... 10030 levels...
	from /usr/local/rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/set.rb:283:in `each'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/configuration.rb:189:in `resolve'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/configuration.rb:150:in `build!'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/base.rb:62:in `build_config'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/base.rb:19:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/client.rb:197:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-core-3.14.0/lib/seahorse/client/base.rb:99:in `new'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/resource.rb:14:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /usr/local/rvm/gems/ruby-2.2.9/gems/railties-4.0.9/lib/rails/commands/console.rb:90:in `start'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/railties-4.0.9/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.2.9/gems/railties-4.0.9/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by raulperezalejo** [comment]
I am having this same issue

ruby 2.3.1
rails  5.0.0
ruby-dicom 0.9.8

**Comment by dicom** [comment]
What is your Operating system, Raul?

And can you also paste your exception trace?

**Comment by dicom** [comment]
I wonder if this is related to Rails 4.

My own project is still on Rails 3, so that may be why I havent experienced this issue.

I am actually planning to upgrade Rails on my project soon, so I will probably encounter it and (hopefully) fix it soonish.

That being said, please feel free to submit a fix yourself, if you are able to. That would definitely be appreciated!
